version: '2'

services:
  bungee:
    image: rehf27/bungeecord
    environment:
      - EULA=true
    
    volumes:
      - ./data/bungeecord:/bungeecord

  lobby:
    image: nimmis/spigot
    ports:
      - 5678:25565
    environment:
      - EULA=true
    volumes:
      - ./data/lobby:/minecraft
  